version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: olzhas

  dj:
    container_name: dj
    build: ./django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: postgres
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: olzhas
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-h", "db", "-p", "5432"]
      interval: 5s
      timeout: 10s
      retries: 5

  ng:
    container_name: ng
    build: angular
    ports:
      - "8080:80"
